---
language: node_js
node_js:
  - 4
  - 6
  - 7
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
script:
  - npm run test-ci
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: "2c40ae32-933f-46ca-9283-4f08942b4419"
install: true
env:
  global:
    - process.env.CI=true
    - CXX=g++-4.8
    - USE_YARN=no
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8