language: node_js
node_js:
- node
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
- CXX=g++-4.8
cache: yarn
before_install: cd react-ui
install:
- yarn upgrade
script:
- yarn test -a
- yarn run build
deploy:
  provider: heroku
  api_key:
    secure: PWIo/yd0TLqz5FLmgQh3HTLo3CoNjWJ0Bv5ndh8ryhTeWwFOipb9hgzCDBgLd1XB8MnB+mbRs2LWAGGejms5F08sK1O3J1z2M4C1rGpY3hOt7/4wic2mg9iHBo7+lonbcSvjvqL7GGmhyRhA+SHTm+SVj/8uz53T/r4Um9sRTKrkYEvSNuxXvI9Lj/RsykNkpH5pHiZn9RwOI5SwLMYn/zQpqlB1pSLXpzbt8z5i8F0jSZhOApRMMW7PYC0CxexcBXE5gsC9cPUb6np8C+P9P0aoJhp/AXLWFFks52eeT3mg/cGRjp3Em1O6rOhzYMVGFUFu/LskvpUb+RA74Fy3qV9GTiUWkAjhfiP4+ra8uo6k55WOShpSLKrUTilADQGwrlXBHqP/lFVOAdN2YqRr03ZIDNok59NFS8EdcF7cecwU0a6tcdEMEX1AeR102toSTSa4hkvoXAoEur4s8MmiXs7wqE4TlbN/hOpzE7HDdb4Dhyp93ohpYqO9hlw9VEqEKJt6qrWxm+dAQ/fnDYFv44acDJlUxp+iEFa+Vubo7RG+PzfmearWJYv5izkOb1QVmgXAn7GTcaizJQMVZRZYys5GqufTQ8Vi+tPVpAkbIxvBJo2EL+f+5MjZ+hn8NZH18d44x0WpauQ7AypC4CAa4l8k5rjokjl3gBNao+decu0=
notifications:
  email: never
  slack:
    secure: mcXbjtNBXZpSF4cZJZXRZSZY1iSLp5Mk8dLoVDf8lfUoUalv159MWsxtr4a33RnBxO3cdTCDAEMav0cpzQLQSojC9kyuMCWroJAwS2HakPV9QKU49Y/izZsR3rBpj4kdU6DvRtCroQOq72pOUsfecfLvpoVr3Zc9G7QYGuOi+k4dOxp/QtDaGz8fIFWQPbk2/QLlmDQApW4aIQs0xcNDKXKd10nw25mRsT0HafPO31GAA4GdN91D5atC1mWHnDq/VUzBYSCORALCJ32lM3XmLNq3uYA7FQ1xzK1wNs+xu/uhhp8KcJ2HPGmhd6WmBU/jRJehpC+7W1cix1kyZYKhaY569d2t6U+WMrVUqxoHC/six1eZL0nLc6HC+9dXDNJkN3yhbKSdBeRiXvp6qR0doW5R4pdH3kv+VYU5rbY3mqztCK2XOA1vBBCD4K1vFpsidoMoB3uSFRQ0+ImIXy5PbfTX9av6iIMyK83N30Xa2L4GOMjcbZJV9Mxnb0WobU3okzr9IJQdnOIHL/YkW/6ws7WS84//GT0V2vuTxJRxIMcmKzoTRtw0p7rC9qQu/2RC16josmbvAC9Zj7EHws4mAn3hAI1TdGG0HZp6PXTlscXwezEon2ySWIIr5etgyjHccOV2jyp13C4s0vkItS4PpDeoeU6hWblNiSNPq2YBH/U=
