---
language: node_js
node_js:
  - 6
  - 7
  - node
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install: true
env:
    - CXX=g++-4.8
cache:
  yarn
  directories:
    - node_modules
install:
  - yarn upgrade
script:
  - yarn run test
  - yarn run build
deploy:
  provider: heroku
  api_key:
    secure: "2c40ae32-933f-46ca-9283-4f08942b4419"
