language: node_js
node_js:
- node
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
- CXX=g++-4.8
cache: yarn
install:
- yarn upgrade
script:
- yarn test -a
- yarn run build
deploy:
  provider: heroku
  api_key:
    secure: PWIo/yd0TLqz5FLmgQh3HTLo3CoNjWJ0Bv5ndh8ryhTeWwFOipb9hgzCDBgLd1XB8MnB+mbRs2LWAGGejms5F08sK1O3J1z2M4C1rGpY3hOt7/4wic2mg9iHBo7+lonbcSvjvqL7GGmhyRhA+SHTm+SVj/8uz53T/r4Um9sRTKrkYEvSNuxXvI9Lj/RsykNkpH5pHiZn9RwOI5SwLMYn/zQpqlB1pSLXpzbt8z5i8F0jSZhOApRMMW7PYC0CxexcBXE5gsC9cPUb6np8C+P9P0aoJhp/AXLWFFks52eeT3mg/cGRjp3Em1O6rOhzYMVGFUFu/LskvpUb+RA74Fy3qV9GTiUWkAjhfiP4+ra8uo6k55WOShpSLKrUTilADQGwrlXBHqP/lFVOAdN2YqRr03ZIDNok59NFS8EdcF7cecwU0a6tcdEMEX1AeR102toSTSa4hkvoXAoEur4s8MmiXs7wqE4TlbN/hOpzE7HDdb4Dhyp93ohpYqO9hlw9VEqEKJt6qrWxm+dAQ/fnDYFv44acDJlUxp+iEFa+Vubo7RG+PzfmearWJYv5izkOb1QVmgXAn7GTcaizJQMVZRZYys5GqufTQ8Vi+tPVpAkbIxvBJo2EL+f+5MjZ+hn8NZH18d44x0WpauQ7AypC4CAa4l8k5rjokjl3gBNao+decu0=
notifications:
  email: never
  slack:
    secure: sMczSEXTovkkNR9hBxYkQ9sa9Uj56J/G5vQAxVynUzL5le7+YuDMSTzqiiHg1s704hfoFZeyuNQEfKGWh+JRz/UOtSsBpU1PE5n/8OcQNk5b+KLmPxjy3exsw3LAzVNLc1W8MWZINhp4TjxcUIUT3XtXETFULWztDURerWhGE4giSFqULDbJlUBXHI0YaL14J7ZSXa0Jgzxd5E198ks+5QAKqWeD2Gwg0b0exSvsQXUJ8zhygk4FeS2/j7S8nQ948Rr90M4pzBnVv8X2etE0Pm03k87p6rvd1vzn3VYxKvgZ9JkHFA8z5lOCiQcYR6LLF6e0mDahRGoWjYsFWWP2ARhS3vjoYZkIKEZ4531aG8W7+MJjjtTXYvuUNza0Bq7FjuQMoXCtHd5XkMBLAxar2aZWlCUlKuk7qr6oOkzKf+/gwgrE26K5ThFyyAjqUzwuiAR1FTq78ItzA11qd+43ugOQg+if77M5PuqGBw4IWgBGuYZH9NNOyxvb64ykhsVGUwacM5qnflF1iEim+anuxrYNwxLZ028iikwjupOXU/pwcXGqMvnya045Smj61G0fMpqhzGB1EmPOdH/iAW9qXGuyWtKeJDSsjQucY4c/2E4BtnETb4d3nEkp4Y76NsqmyFzKpL18pVe0vIOHToOn7mvfXDNHdgf5GafPoXKymtQ=
