language: node_js
node_js:
- node
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
- CXX=g++-4.8
cache: yarn
install:
- yarn upgrade
- yarn global add standard #TODO: add back in when it works.
before_script:
- standard --fix
script:
- yarn run test
- yarn run build
deploy:
  provider: heroku
  api_key:
    secure: PWIo/yd0TLqz5FLmgQh3HTLo3CoNjWJ0Bv5ndh8ryhTeWwFOipb9hgzCDBgLd1XB8MnB+mbRs2LWAGGejms5F08sK1O3J1z2M4C1rGpY3hOt7/4wic2mg9iHBo7+lonbcSvjvqL7GGmhyRhA+SHTm+SVj/8uz53T/r4Um9sRTKrkYEvSNuxXvI9Lj/RsykNkpH5pHiZn9RwOI5SwLMYn/zQpqlB1pSLXpzbt8z5i8F0jSZhOApRMMW7PYC0CxexcBXE5gsC9cPUb6np8C+P9P0aoJhp/AXLWFFks52eeT3mg/cGRjp3Em1O6rOhzYMVGFUFu/LskvpUb+RA74Fy3qV9GTiUWkAjhfiP4+ra8uo6k55WOShpSLKrUTilADQGwrlXBHqP/lFVOAdN2YqRr03ZIDNok59NFS8EdcF7cecwU0a6tcdEMEX1AeR102toSTSa4hkvoXAoEur4s8MmiXs7wqE4TlbN/hOpzE7HDdb4Dhyp93ohpYqO9hlw9VEqEKJt6qrWxm+dAQ/fnDYFv44acDJlUxp+iEFa+Vubo7RG+PzfmearWJYv5izkOb1QVmgXAn7GTcaizJQMVZRZYys5GqufTQ8Vi+tPVpAkbIxvBJo2EL+f+5MjZ+hn8NZH18d44x0WpauQ7AypC4CAa4l8k5rjokjl3gBNao+decu0=
notifications:
  email: never
  slack:
    secure: m0YnlenpHV4gGtj9ZA/0GqjL2QAWdr7sPEMIbu4vI32XcsQ1Yo5uPBhk7G+CC3Gf4QbaiPGR8TTbVS63RZbxkKWCEuZ2xztLsMKdkxlbNuENZzXaobJjCbSyjiI+nH8M1S144EQ9JTWGI96XbH0zVEq/fOGn5vMEIG+hngCS8AmflKtaZCquCN9t3ePwKOYZlXXI1u0RkZGoE/pVBDpKuX21YNDna0U27glqCwvSop8SIq5yuX91TOJ26lax5YnESuiJypT13Lnntma4rbjj5ZAFGl4GtdZ3FD4sdWqrBIFdvBJGKwEEFZLCwJCkR0F36AtFC/aQumCEz+yqJCiiBLuMSJY53O3cGHrL6ttM5cfFZJLUko61QFnFJ6a729ns9Ou2bQy6wNNhf+Rdgj3Y2nKNCkfLxM1E2RILYFv/CEZiEgaYxVgbBg88rzBxg6qahTbBPn+z9j47O6TJsEOfoxjok65ivRkyrCUVHyLVvjVFpaQ0s6sR3x1OAZRuZh9pgnUkXMQX76EUZmSrhxj/nKmigs+JEdtjwi83O3gSWpWPjdvZyMiwogyjO6evig+aEM26x9wFMP3VWjwrFaiO+sCNwlH8ohNCYorc/P7mxWx5qoANDw9jpuYYFgv0NlgZHnG2IiZsx9uThozJr/7Mfj53WrpiqbtrL9p3zpP/0wg=
