language: node_js
node_js:
- node
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
- CXX=g++-4.8
cache: yarn
install:
- yarn upgrade
script:
- yarn test -a
- yarn run build
deploy:
  provider: heroku
  api_key:
    secure: PWIo/yd0TLqz5FLmgQh3HTLo3CoNjWJ0Bv5ndh8ryhTeWwFOipb9hgzCDBgLd1XB8MnB+mbRs2LWAGGejms5F08sK1O3J1z2M4C1rGpY3hOt7/4wic2mg9iHBo7+lonbcSvjvqL7GGmhyRhA+SHTm+SVj/8uz53T/r4Um9sRTKrkYEvSNuxXvI9Lj/RsykNkpH5pHiZn9RwOI5SwLMYn/zQpqlB1pSLXpzbt8z5i8F0jSZhOApRMMW7PYC0CxexcBXE5gsC9cPUb6np8C+P9P0aoJhp/AXLWFFks52eeT3mg/cGRjp3Em1O6rOhzYMVGFUFu/LskvpUb+RA74Fy3qV9GTiUWkAjhfiP4+ra8uo6k55WOShpSLKrUTilADQGwrlXBHqP/lFVOAdN2YqRr03ZIDNok59NFS8EdcF7cecwU0a6tcdEMEX1AeR102toSTSa4hkvoXAoEur4s8MmiXs7wqE4TlbN/hOpzE7HDdb4Dhyp93ohpYqO9hlw9VEqEKJt6qrWxm+dAQ/fnDYFv44acDJlUxp+iEFa+Vubo7RG+PzfmearWJYv5izkOb1QVmgXAn7GTcaizJQMVZRZYys5GqufTQ8Vi+tPVpAkbIxvBJo2EL+f+5MjZ+hn8NZH18d44x0WpauQ7AypC4CAa4l8k5rjokjl3gBNao+decu0=
notifications:
  email: never
  slack:
    rooms:
      secure: oOnxP6c/aAEZ1BXI4K/BQ7jVYXZuzZs5lSvTfIuw3tJru2kP726+tdEDX2RZh49EshWVGygAj+MRzWk5Aj1xMRpQxCcjF9qa2PpADmP04XHWMIPRa8xeDepBrT6up3mmO/9sMB5si9+qaLpmSiUN0K+fBE4fhh9VnrnTSfoacVhZ4ax7CJ0k6rNrs7rTKiSW5OS12edxFFC7bjVF9e8kSIpFUrTr97/PiBxv99Y/KMG8i58NZx1KRGFYUe5z/fAtUldr5Q8XuOC+DpLhRxx9ZZfSFbEzE+fiYT7EHfYBWNvA63e2p/Waw1XABT1Ql/AvVn91fM8IgQ7auReGGmDGY2jfjJ1FsiwCz9S5couf5SwN58AZfWkq+kjJc1it1BvL/0MxOqIUP2tUHDEVVVp4qmTBi4VIi0Eh+OIgp1KFeQUWbv8jwl9SK6PStpXo6J72ZDdqcb305K7vk0cZgJ++dZTtczlBnW0UR2ESIPypTh+C+UP3eH+hbLEa7rw4VK9Rt2LKoxQMLCSG/+I4x7+0B5ep6NwyhptfiUyMnWZGvKHen5S0DF8xbkDDYPYjJHFfDECbGVB2IuKeXHPFXQKMQidCskISlAXfa6KnOfvp1tO5BOMd3ikEzEzMLF08ug8Zo8mfh+pmoAFs7CO5rDqi3R6MdM7mfk7m0Wb1Iadu32I=
